### ISSUE TITLE
ERROR - 422 Unprocessable Entity

### ISSUE THREAD

**Issue by hbokh** [timogoebel/foreman_provision#17]
Both in my own config AND in the one provided at "inovex blog" / [Foreman Provision: A Comfortable Resource Management Tool for Foreman](https://www.inovex.de/blog/foreman-provision-a-comfortable-resource-management-tool-for-foreman/), I receive an error like this:

```
# ./bin/foreman-provision --auth_credentials=conf/foreman.yaml --config_file=conf/config.yaml --verbose
I, [2016-11-06T15:54:18.160777 #26382]  INFO -- : Creating ForemanProvision::Subnet "default"
I, [2016-11-06T15:54:18.819490 #26382]  INFO -- : Creating ForemanProvision::Domain "vagrant.inovex.de"
I, [2016-11-06T15:54:19.143171 #26382]  INFO -- : Creating ForemanProvision::Hostgroup "Test-Hosts"
I, [2016-11-06T15:54:20.550855 #26382]  INFO -- : Creating ForemanProvision::Host "test1.vagrant.inovex.de"
E, [2016-11-06T15:54:20.898614 #26382] ERROR -- : Error while processing provisoning: "#<RestClient::UnprocessableEntity: 422 Unprocessable Entity>"!
/usr/local/share/gems/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:223:in `exception_with_response'
/usr/local/share/gems/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:103:in `return!'
/usr/local/share/gems/gems/rest-client-2.0.0/lib/restclient/request.rb:860:in `process_result'
/usr/local/share/gems/gems/rest-client-2.0.0/lib/restclient/request.rb:776:in `block in transmit'
/usr/share/ruby/net/http.rb:852:in `start'
/usr/local/share/gems/gems/rest-client-2.0.0/lib/restclient/request.rb:766:in `transmit'
/usr/local/share/gems/gems/rest-client-2.0.0/lib/restclient/request.rb:215:in `execute'
/usr/local/share/gems/gems/rest-client-2.0.0/lib/restclient/request.rb:52:in `execute'
/usr/local/share/gems/gems/rest-client-2.0.0/lib/restclient/resource.rb:67:in `post'
/usr/local/share/gems/gems/foreman_api-0.1.11/lib/foreman_api/base.rb:78:in `http_call'
/usr/local/share/gems/gems/foreman_api-0.1.11/lib/foreman_api/base.rb:61:in `perform_call'
/usr/local/share/gems/gems/foreman_api-0.1.11/lib/foreman_api/resources/host.rb:63:in `create'
/root/develop/foreman_provision/lib/foreman_provision/base_resource.rb:13:in `create'
/root/develop/foreman_provision/lib/foreman_provision/host.rb:90:in `create'
/root/develop/foreman_provision/lib/foreman_provision/provision.rb:52:in `manage_resource'
/root/develop/foreman_provision/lib/foreman_provision/provision.rb:268:in `block in run'
/root/develop/foreman_provision/lib/foreman_provision/provision.rb:230:in `each'
/root/develop/foreman_provision/lib/foreman_provision/provision.rb:230:in `run'
./bin/foreman-provision:55:in `<main>'
Error while processing provisoning: "#<RestClient::UnprocessableEntity: 422 Unprocessable Entity>"!
```

Running in test-mode shows no possible issue(s):

```# ./bin/foreman-provision --auth_credentials=conf/foreman.yaml --config_file=conf/config.yaml --verbose --test
I, [2016-11-06T15:58:30.345649 #26727]  INFO -- : Running provision in test mode
I, [2016-11-06T15:58:30.470354 #26727]  INFO -- : Skipping - ForemanProvision::Subnet "default" already exists!
I, [2016-11-06T15:58:30.551276 #26727]  INFO -- : Skipping - ForemanProvision::Domain "vagrant.inovex.de" already exists!
I, [2016-11-06T15:58:30.651724 #26727]  INFO -- : Skipping - ForemanProvision::Hostgroup "Test-Hosts" already exists!
I, [2016-11-06T15:58:30.745355 #26727]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a1", :name=>"test1.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-06T15:58:30.838915 #26727]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a2", :name=>"test2.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-06T15:58:30.932525 #26727]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a3", :name=>"test3.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-06T15:58:31.056828 #26727]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a4", :name=>"test4.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-06T15:58:31.149408 #26727]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a5", :name=>"test5.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-06T15:58:31.247472 #26727]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a6", :name=>"test6.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-06T15:58:31.343319 #26727]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a7", :name=>"test7.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-06T15:58:31.436212 #26727]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a8", :name=>"test8.vagrant.inovex.de", :ensure=>"present"}
```

Any clues?
Tested with `commit 5944904` from Oct. 27th 2015 on Foreman 1.13.

**Comment by marcohelmerich** [comment]
Hey there, foreman_provision is over a year old and uses api version v1. I also think, there were serveral breaking changes in the foreman api between Oct 27th 2015 and Foreman 1.13. Foreman production.log should tell you more details about the unprocessable entity. But maybe you should look into API Version 2 instead.

**Comment by timogoebel** [comment]
@hbokh : At least host creation should still work with Foreman 1.13. The error might be, that Foreman cannot save the host because it is invalid for whatever reason. I just pushed a commit, which improves the error handling. Can you try it with this code? It should show, what's going on.

**Comment by hbokh** [comment]
Pulled the latest commit (commit 765b33a) and first ran in test-mode:

```
# ./bin/foreman-provision --auth_credentials=conf/foreman.yaml --config_file=conf/config.yaml --verbose --test
I, [2016-11-11T09:49:47.424929 #13545]  INFO -- : Running provision in test mode
I, [2016-11-11T09:49:47.545000 #13545]  INFO -- : Skipping - ForemanProvision::Subnet "default" already exists!
I, [2016-11-11T09:49:47.665067 #13545]  INFO -- : Skipping - ForemanProvision::Domain "vagrant.inovex.de" already exists!
I, [2016-11-11T09:49:47.790837 #13545]  INFO -- : Skipping - ForemanProvision::Hostgroup "Test-Hosts" already exists!
I, [2016-11-11T09:49:47.890719 #13545]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a1", :name=>"test1.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-11T09:49:47.989834 #13545]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a2", :name=>"test2.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-11T09:49:48.090838 #13545]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a3", :name=>"test3.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-11T09:49:48.213271 #13545]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a4", :name=>"test4.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-11T09:49:48.309284 #13545]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a5", :name=>"test5.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-11T09:49:48.402268 #13545]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a6", :name=>"test6.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-11T09:49:48.493537 #13545]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a7", :name=>"test7.vagrant.inovex.de", :ensure=>"present"}
I, [2016-11-11T09:49:48.587898 #13545]  INFO -- : Would have created ForemanProvision::Host {:build=>true, :hostgroup=>"Test-Hosts", :mac=>"06:10:9f:dc:aa:a8", :name=>"test8.vagrant.inovex.de", :ensure=>"present"}
```

Now the non-test at least does not show the ruby-errors but is still failing on the inovex example-config:

```
# ./bin/foreman-provision --auth_credentials=conf/foreman.yaml --config_file=conf/config.yaml --verbose
I, [2016-11-11T09:49:57.515356 #13552]  INFO -- : Skipping - ForemanProvision::Subnet "default" already exists!
I, [2016-11-11T09:49:57.597794 #13552]  INFO -- : Skipping - ForemanProvision::Domain "vagrant.inovex.de" already exists!
I, [2016-11-11T09:49:57.703916 #13552]  INFO -- : Skipping - ForemanProvision::Hostgroup "Test-Hosts" already exists!
I, [2016-11-11T09:49:57.797885 #13552]  INFO -- : Creating ForemanProvision::Host "test1.vagrant.inovex.de"
E, [2016-11-11T09:49:58.160819 #13552] ERROR -- : HTTP Error: {
  "error": {"id":null,"errors":{"operatingsystem_id":["can't be blank"]},"full_messages":["Operatingsystem can't be blank"]}
}
```

**Comment by timogoebel** [comment]
@hbokh : Please check, that the Host actually has an operating system set. I don't know the example, but judging from a brief look you might want to check if the OS is correctly set on the Hostgroup "Test-Hosts".

**Comment by hbokh** [comment]
Danke Timo. You can check the mentioned example over here: [Foreman Provision: A Comfortable Resource Management Tool for Foreman](https://www.inovex.de/blog/foreman-provision-a-comfortable-resource-management-tool-for-foreman/).

As you can see `operatingsystem` is defined in `:hostgroups:` as `CentOS 7.0` and the hostgroup is included for every entry under `:hosts:`.

**Comment by timogoebel** [comment]
Yes, but that doesn't necessarily mean that the OS actually exists. Please check in the Foreman UI that the hostgroup really has the OS set.

**Comment by hbokh** [comment]
Never thought about that in the first place...
Working fine now:

```
# ./bin/foreman-provision --auth_credentials=conf/foreman.yaml --config_file=conf/config.yaml --verbose
I, [2016-11-11T13:02:54.554932 #20761]  INFO -- : Skipping - ForemanProvision::Subnet "default" already exists!
I, [2016-11-11T13:02:54.667180 #20761]  INFO -- : Skipping - ForemanProvision::Domain "vagrant.inovex.de" already exists!
I, [2016-11-11T13:02:54.807218 #20761]  INFO -- : Skipping - ForemanProvision::Hostgroup "Test-Hosts" already exists!
I, [2016-11-11T13:02:54.932710 #20761]  INFO -- : Creating ForemanProvision::Host "test1.vagrant.inovex.de"
I, [2016-11-11T13:02:55.620799 #20761]  INFO -- : Creating ForemanProvision::Host "test2.vagrant.inovex.de"
I, [2016-11-11T13:02:56.249920 #20761]  INFO -- : Creating ForemanProvision::Host "test3.vagrant.inovex.de"
I, [2016-11-11T13:02:56.824534 #20761]  INFO -- : Creating ForemanProvision::Host "test4.vagrant.inovex.de"
I, [2016-11-11T13:02:57.412967 #20761]  INFO -- : Creating ForemanProvision::Host "test5.vagrant.inovex.de"
I, [2016-11-11T13:02:58.057071 #20761]  INFO -- : Creating ForemanProvision::Host "test6.vagrant.inovex.de"
I, [2016-11-11T13:02:58.641013 #20761]  INFO -- : Creating ForemanProvision::Host "test7.vagrant.inovex.de"
I, [2016-11-11T13:02:59.211364 #20761]  INFO -- : Creating ForemanProvision::Host "test8.vagrant.inovex.de"
```

I'll try with my own config next.
Vielen dank!
